server.servlet.context-path=/api
spring.output.ansi.enabled=always

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.org.hibernate.flushMode=always

# run any sql scripts from schema.sql
spring.sql.init.mode=always

# So app starts despite "table already exists" errors.
spring.sql.init.continue-on-error=true

spring.jpa.show-sql=false

#logging-level
logging.level.ua.sinaver.web3=DEBUG

# error handling
server.error.include-stacktrace=never

#gcp

#spring.cloud.gcp.config.project-id=payflow-393217
#spring.cloud.gcp.sql.instance-connection-name=payflow-393217:europe-west2:payflow-db
#spring.cloud.gcp.sql.database-name=payflow_db


# for local mysql
spring.datasource.url=jdbc:mysql://mysql:3306/upflow_db
spring.datasource.username=root
spring.datasource.password=password
